name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

jobs:
  script:
    runs-on: ubuntu-latest

    steps:
      - name: Display misc information
        run: |
          echo "The job was automatically triggered by a ${{ github.event_name }} event."
          echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Checkout result
        run: echo "The ${{ github.repository }} repository has been cloned to the runner."

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Display first and last name
        run: echo Illia I. is testing this
